#!/bin/sh +x

echo "LIGHTNING_USER_ID=$LIGHTNING_USER_ID
LIGHTNING_API_KEY=$LIGHTNING_API_KEY
LIGHTNING_USERNAME=$LIGHTNING_USERNAME
LIGHTNING_TEAMSPACE=$LIGHTNING_TEAMSPACE
LIGHTNING_CLUSTER_ID=$LIGHTNING_CLUSTER_ID
LIGHTNING_ORG=$LIGHTNING_ORG"
